apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: monitoring
spec:
  selector:
    app: pihole-exporter
  ports:
    - name: http-metrics
      port: 9617
      targetPort: http-metrics
  type: ClusterIP
