apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-exporter/base
  - speedtest-exporter/base
  - pve-exporter/base
  - pihole-exporter/base
  - external-services/base
