apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yaml
  - pvc.yaml
  - templates-configmap.yaml
  - deployment.yaml
  - service.yaml
generators:
  - configmap-generator.yaml
