apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  selector:
    app: speedtest-exporter
  ports:
    - name: http
      port: 9798
      targetPort: 9798
  type: ClusterIP
