apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-local-path-provisioner
  namespace: custom-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-local-path-provisioner
  template:
    metadata:
      labels:
        app: custom-local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
        - name: local-path-provisioner
          image: "rancher/local-path-provisioner:v0.0.32"
          imagePullPolicy: IfNotPresent
          command: ["local-path-provisioner"]
          args:
            - "start"
            - "--config"
            - "/etc/config/config.json"
            - "--configmap-name"
            - "custom-local-path-config"
          env:
            - name: PROVISIONER_NAME
              value: "custom.local/local-path"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: "/etc/config/"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: custom-local-path-config
