apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app: pve-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter:latest
          ports:
            - name: http
              containerPort: 9221
          volumeMounts:
            - name: pvecfg
              mountPath: /etc/prometheus
              readOnly: true
      volumes:
        - name: pvecfg
          secret:
            secretName: pve-config
            items:
              - key: pve.yml
                path: pve.yml
