apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app: pve-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter:latest
          ports:
            - name: http
              containerPort: 9221
          env:
            - name: PVE_USER
              value: "monitoring@pve"
            - name: PVE_TOKEN_NAME
              value: "monitoring-token"
            - name: PVE_VERIFY_SSL
              value: "false"
            - name: PVE_TOKEN_VALUE
              valueFrom:
                secretKeyRef:
                  name: pve-exporter-secret
                  key: PVE_TOKEN_VALUE
