apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  selector:
    app: pve-exporter
  ports:
    - name: http
      port: 9221
      targetPort: 9221
  type: ClusterIP
